import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { getMessages, getLocale } from 'next-intl/server';

import { signIn } from "auth"
import AuthProvider from "@/components/providers/SessionProvider";
import { NextIntlClientProvider } from "next-intl";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const metadata: Metadata = {
    title: "Inventario asamblea",
    description: "Generated by create next app",
};

export default async function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const locale = await getLocale();
    const messages = await getMessages();
    return ( 
        <html lang="{locale}">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <main className="min-h-screen bg-[#0a0a0c] text-white selection:bg-purple-500/30">
                    <AuthProvider>
                        <NextIntlClientProvider messages={messages}>
                            {children}
                        </NextIntlClientProvider>
                    </AuthProvider>
                </main>
            </body>
        </html>
    );
}
