'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { useState } from "react";
import { SessionProvider } from "next-auth/react";



const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const metadata: Metadata = {
	title: "Inventario asamblea",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	const [isSidebarOpen, setIsSidebarOpen] = useState(false);

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider>
					{children}
				</SessionProvider>
			</body>
		</html>
	);
}
