'use client';
import AuthProvider from "@/components/providers/SessionProvider";
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import Navbar from "@/components/dashboard/navbar/navbar";
import Sidebar from "@/components/dashboard/sidebar/sidebar";
import { Metadata } from "next";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import Head from "next/head";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const metadata: Metadata = {
    title: "Inventario asamblea",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const [isSidebarOpen, setSidebarOpen] = useState(true); // Default to true

    // Use an effect to close it on small screens after mounting
    useEffect(() => {
        if (window.innerWidth < 1024) setSidebarOpen(false);
    }, []);

    const toggleSidebar = () => setSidebarOpen(!isSidebarOpen);
    return (
        <AuthProvider>
            <html lang="en">
                <Head>
                    <title>
                        {metadata.title?.toString()} || Inventario Asamblea
                    </title>
                </Head>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-black`}>
                    <div className="flex h-screen overflow-hidden">
                        {/* SIDEBAR */}
                        <Sidebar isOpen={isSidebarOpen} onToggle={toggleSidebar} />

                        {/* MAIN AREA */}
                        <div className="flex-1 flex flex-col overflow-hidden">
                            {/* NAVBAR */}
                            <Navbar
                                onToggle={toggleSidebar}
                                isSidebarOpen={isSidebarOpen}
                            />

                            {/* CONTENT */}
                            <main className="flex-1 overflow-x-hidden overflow-y-auto p-6 bg-[#F2F2F2]">
                                {children}
                            </main>
                        </div>
                    </div>
                </body>
            </html>
        </AuthProvider>
    );
}