'use client';
import AuthProvider from "@/components/providers/SessionProvider";
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import Navbar from "@/components/dashboard/navbar/navbar";
import Sidebar from "@/components/dashboard/sidebar/sidebar";
import { Metadata } from "next";
import { useSession } from "next-auth/react";
import { useEffect, useState } from "react";
import Head from "next/head";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const metadata: Metadata = {
    title: "Inventario asamblea",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const [isSidebarOpen, setSidebarOpen] = useState(true); // Default to true

    // Use an effect to close it on small screens after mounting
    useEffect(() => {
        if (window.innerWidth < 1024) setSidebarOpen(false);
    }, []);

    const toggleSidebar = () => setSidebarOpen(!isSidebarOpen);
    return (
        <AuthProvider>
            <html lang="en">
                <Head>
                    <title>
                        {metadata.title?.toString()} || Inventario Asamblea
                    </title>
                </Head>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-black`}>
                    <div className="flex h-screen bg-surface overflow-hidden">
                        {/* SIDEBAR */}
                        <Sidebar isOpen={isSidebarOpen} onToggle={toggleSidebar} />

                        {/* MAIN VIEWPORT */}
                        <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
                            <div className={` flex flex-col h-full transition-all duration-500 ease-in-out ${isSidebarOpen ? 'md:pl-72' : 'md:pl-20'} `}>
                                {/* NAVBAR */}
                                <Navbar
                                    onToggle={toggleSidebar}
                                    isSidebarOpen={isSidebarOpen}
                                />

                                {/* CONTENT AREA */}
                                <main className="flex-1 overflow-x-hidden overflow-y-auto p-4 md:p-8">
                                    <div className="max-w-7xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-700">
                                        {children}
                                    </div>
                                </main>
                            </div>
                        </div>
                    </div>
                </body>
            </html>
        </AuthProvider>
    );
}